language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: fxIlZuncV86SIwJGaXkTqgYIAHYT5rq8BO0cU4zqI6NP7BlN/DXTR1yXCbhVIazB62vfkvHTvwEvEOH/QZZOiWmHre5CBpWpf52u7n2pnpl3G0Gi7vL6gOsx497l7ddE6Onq6yBO1tSLfVe6Q4uw6cvbzLF72+/qs8Xg4z+V5f+CJyaozalxEY9l0YWTGfk/vzCkuQyYg5L5cqvWCRNmvIyQG5+vAX0HxgI7Q+A+3QpToBWZNsdthBq4HM26MPDNKgDLhmFTrXX7xxDCh9Lo67ADaeWGZLprxgrHGLW9wkbXTtTGBjFmXtut3txhdVkMCHk8a7NXANd+hCDA59CeUGFf0toylfzDCArqc7WoOgTTTD8Q69ldFKAd07Jctk02Zl2OJRjiv+5iWznXdAFMO6hVP4lqVj5eet5mfInfUg0Bvh3Limy33fmX5VWklzvSh1ZvA6Pd2f6dtRwxPiAgi3z4RzP1GkB+HtC6LFmfrTS9AhDY4G9WOauRODKj+p+KONexuan4m6v7ijeY0+YcZ7n5Rzz7sobFaE3zrYNIfzfeZC3SzvVdmRE6p6QjpDstjRd5hk9X9AFF8CfWGvNU2N8fLDZq9ToyNWvBhKNwQytjjOQgeSrs1j4oBIDU6NzVswfDtPuUB1V0VI34n2hGf2FJSBOwTd9u82W7ynOHcd4=
